export const ADD_FAVOURITE = "ADD_FAVOURITE"
export const DELETE_FAVOURITES = "DELETE_FAVOURITES"
export const FILTER = "FILTER"
export const ORDER = "ORDER"

export const GETFAVORITES = "GETFAVORITES"